name: Super-Linter

on:
  push:
    branches:
      - master  # Change this to your main branch name if needed

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          DEFAULT_BRANCH: master  # Change this to your default branch name if needed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
