name: Super-Linter

on:
  push:
    branches:
      - master  # Change this to your main branch name if needed

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master  # Change this to your default branch name if needed
